status = [
  "docs",
  "Linux python:3.6-slim",
  "Linux python:3.7-slim",
  "Windows python:3.6-windowsservercore",
  "Windows python:3.7-windowsservercore",
  "macOS PYTHON:3.6.8",
  "macOS PYTHON:3.7.2",
  "pep517",
]

delete_merged_branches = true
